# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: langchain-mcp-adapters
  version: "0.1.11"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/langchain_mcp_adapters-${{ version }}.tar.gz
  sha256: a217c49086b162344749f7f99a148fc12482e2da8e0260b2e35fc93afb31b38d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pdm-backend
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - langchain-core >=0.3.36,<0.4
    - mcp >=1.9.2
    - typing_extensions >=4.14.0

tests:
  - python:
      imports:
        - langchain_mcp_adapters
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Make Anthropic Model Context Protocol (MCP) tools compatible with LangChain and LangGraph agents.
  license: MIT
  license_file: LICENSE
  homepage: https://pypi.org/project/langchain-mcp-adapters/
  repository: https://github.com/langchain-ai/langchain-mcp-adapters

extra:
  recipe-maintainers:
    - rxm7706
